In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
A.shape

(3, 2)

In [12]:
B = A.T
B

array([[1, 3, 5],
       [2, 4, 6]])

In [13]:
B.shape

(2, 3)

In [14]:
A.dot(B)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])